### ISSUE TITLE
AWS SAM CLI instructions recommends invalid BuildProperties

### ISSUE THREAD

**Issue by ianwremmel** [prisma/prisma2-docs#5525]
The instructions at https://www.prisma.io/docs/guides/deployment/serverless/deploy-to-aws-lambda#loading-required-files say to add the following to each function's Metadata.BuildProperties:

```yml
Loader:
  - .prisma=file
  - .so.node=file
AssetNames: '[name]'
```

However, in so doing, sam build fails with 

```
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Invalid option in build() call: "loader:"
```

and 

```
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Invalid option in build() call: "asset-names:"
```
